# The west manifest file for ti-zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  self : 
    path: ti-zephyr

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: TexasInstruments
      url-base: https://github.com/TexasInstruments
    - name: babblesim
      url-base: https://github.com/BabbleSim

  defaults: 
    remote: zephyrproject-rtos

  group-filter: [-babblesim, -optional, -testing]

  #
  # Please add items below based on alphabetical order
  # zephyr-keep-sorted-start re(^\s+\- name:)
  projects:
    - name: zephyr
      remote: TexasInstruments
      path: zephyr
      url: https://github.com/TexasInstruments/zephyr
      revision: main
      import: true
    - name: zephyr-xenlib
      revision: 8b13d0b709314b7de6cb5877c286d52e71095cc8
      path: modules/lib/zephyr-xenlib
  # zephyr-keep-sorted-stop
